### ISSUE TITLE
Readme/setup for self hosting

### ISSUE THREAD

**Issue by danielnil** [christoabrown/group-ironmen-tracker#1]
The application looks amazing! Will there be a setup guide for self hosting the front and backend?

**Comment by christoabrown** [comment]
Yep, I intend on writing up something on how to set that up for people who do not want to use the default public server. I will make sure to mention this issue when I have that ready.

**Comment by danielnil** [comment]
Thanks!

**Comment by chrisleee** [comment]
As discussed in Discord, I'll follow up with a Docker image and docker-compose file.

**Comment by chrisleee** [comment]
Added a Docker image, docker-compose file, and instructions for self-hosting with Docker as part of https://github.com/christoabrown/group-ironmen/pull/2.
