### ISSUE TITLE
Placeholder item counted as 1 item

### ISSUE THREAD

**Issue by the-eater** [christoabrown/group-ironmen-tracker#12]
I am using placeholders in the bank, however this is shown as 1 item on the tracker, see screenshots e.g. (I am, `e_ter`):
![Screenshot of my inventory, containing no silver bars](https://user-images.githubusercontent.com/1922630/166147218-891e08ae-c6c7-4db9-b7c1-f8a8fa35a8dc.png)
![Screenshot of bank showing only silver bar in placeholder](https://user-images.githubusercontent.com/1922630/166147219-05e911d7-55a5-4bf0-9e52-7b56de7ade1f.png)

![Screenshot of tracker showing a single bar owned](https://user-images.githubusercontent.com/1922630/166147226-55f49737-22fe-4ccc-99cc-a835029cc437.png)

**Comment by chrisleee** [comment]
Will be fixed in this PR - https://github.com/runelite/plugin-hub/pull/2637
Once it's merged in you might have to open the bank on each character for the placeholders to go away

**Comment by the-eater** [comment]
thanks for the quick work! :)
