### ISSUE TITLE
Salve(ei) shows as separate item

### ISSUE THREAD

**Issue by PJGJ210** [christoabrown/group-ironmen-tracker#29]
Not sure if this is just an instance ID issue (in which case no issue) or how it is displayed via site. 

![image](https://user-images.githubusercontent.com/16944807/219086623-aa634e6c-0144-4a08-abd5-3c097b547f3f.png)
![image](https://user-images.githubusercontent.com/16944807/219086697-8773f09d-6752-4e11-b88d-4ec97a0df730.png)

**Comment by christoabrown** [comment]
There are different item ids depending on what you used to imbue the salve amulet. nightmare zone, soul wars, pvp arena
