### ISSUE TITLE
Graphs are broken since yesterday

### ISSUE THREAD

**Issue by xabec** [christoabrown/group-ironmen-tracker#36]
self explanatory title. Something happened with data since yesterday.

![image](https://github.com/christoabrown/group-ironmen-tracker/assets/88092222/0d52c803-71ba-4c95-bc37-f44acd58f87b)

![image](https://github.com/christoabrown/group-ironmen-tracker/assets/88092222/73c42d6a-193c-48e2-81de-2abbb9e5a861)

![image](https://github.com/christoabrown/group-ironmen-tracker/assets/88092222/8394b97e-06c0-4c23-9ee0-3f44be4ed462)

**Comment by xabec** [comment]
stat pulling is incorrect too. 

![image](https://github.com/christoabrown/group-ironmen-tracker/assets/88092222/10320fdd-c695-46dd-a629-8a6f6974338a)

wc & prayer levels are incorrect. Total xp is incorrect too.

New xp is tracked correctly.

**Comment by christoabrown** [comment]
Could you clarify if this is on groupiron.men or self hosted?
